import React from 'react';
//import { useQuestionStore } from '../store';

function BgSpreadLines() {

   return (
    <svg className="absolute w-full h-full top-0 left-0 pointer-events-none z-0" xmlns="http://www.w3.org/2000/svg">
    <line
        x1="20%"
        y1="65.3%"
        x2="80%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="20%"
        y1="58.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="20%"
        y1="51.3%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="25.8%"
        y1="47.3%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="28%"
        y1="41.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="31%"
        y1="36%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="37.9%"
        y1="38.4%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="41%"
        y1="33.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="45.2%"
        y1="30%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
 {/*other side*/}
     <line
        x1="80%"
        y1="58.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="76.2%"
        y1="53%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="74.2%"
        y1="47.3%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="72%"
        y1="41.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="67.8%"
        y1="38%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="64%"
        y1="34%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="59%"
        y1="33.5%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    <line
        x1="54.8%"
        y1="30%"
        x2="50%"
        y2="65.3%"
        stroke="black"
        strokeWidth="1"
      />
    </svg>
      );
}

export default BgSpreadLines;